module.exports = {
  apps: [
    {
      name: 'tg-storage-api',
      script: 'artisan',
      args: 'serve --host=0.0.0.0 --port=8000',
      interpreter: 'php',
      interpreter_args: '',
      cwd: __dirname,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      env: {},
    },
    {
      name: 'tg-storage-queue-telegram',
      script: 'artisan',
      args: 'queue:listen --queue=telegram --tries=3 --backoff=10,30,60',
      interpreter: 'php',
      cwd: __dirname,
      watch: false,
      autorestart: true,
      max_restarts: 20,
    },
    {
      name: 'tg-storage-queue-default',
      script: 'artisan',
      args: 'queue:listen --queue=default --tries=3',
      interpreter: 'php',
      cwd: __dirname,
      watch: false,
      autorestart: true,
      max_restarts: 20,
    },
    {
      name: 'tg-storage-reverb',
      script: 'artisan',
      args: 'reverb:start --host=0.0.0.0 --port=8080',
      interpreter: 'php',
      cwd: __dirname,
      watch: false,
      autorestart: true,
      max_restarts: 10,
    },
    {
      name: 'tg-storage-scheduler',
      script: 'artisan',
      args: 'schedule:work',
      interpreter: 'php',
      cwd: __dirname,
      watch: false,
      autorestart: true,
      max_restarts: 10,
    },
    {
      name: 'tg-storage-frontend',
      script: 'npm',
      args: 'run dev',
      interpreter: 'node',
      cwd: __dirname + '/frontend',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      env: {
        NODE_ENV: 'development',
      },
    },
  ],
}
